# Generated by Django 6.0.3 on 2026-04-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_causes_report_description_report_prevention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='language',
            field=models.CharField(default='en', max_length=5),
        ),
    ]
